# Generated by Django 2.0.4 on 2018-04-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailybey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='body',
        ),
    ]
