# Generated by Django 2.0.4 on 2018-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailybey', '0003_auto_20180414_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
