# Generated by Django 2.0.4 on 2018-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailybey', '0006_auto_20180414_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
